# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- task: VSBuild@1
  inputs:
    solution: '**\TestApp.sln'
    vsVersion: '17.0'
    platform: 'x64'
    configuration: 'Debug'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/TestApp/x64/Debug'
    ArtifactName: 'drop'
    publishLocation: 'Container'